### ISSUE TITLE
scraper

### ISSUE THREAD

**Issue by Szymczek** [Solvro/web-planer#67]

**Comment by Szymczek** [comment]
MEGA robota

**Comment by Szymczek** [comment]
przemyśleć linki do poszczególnych planów - plany moga sie aktualizować w ciagu dnia lub w tygodniu, wiec bedzie trzeba powtórzyc kilka razy te scrapy

**Comment by Szymczek** [comment]
scrapowanie raz na dzien

na teraz tylko rejestracji bez przedmiotow w tych rejestracjach

**Comment by unewMe** [comment]
Wypada poprawić - dodać wielowątkowość
